version: '3.1'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: eventator_db
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: y
      SA_PASSWORD: 72F9EE388378F09B48F62CCBFFECA7D350196308A390654B74FAE5465951C185
      MSSQL_PID: Express
      MSSQL_BACKUP_DIR: /usr/src/Eventator/database/backup
      MSSQL_DATA_DIR: /usr/src/Eventator/database/data
      MSSQL_LOG_DIR: /usr/src/Eventator/database/log
    volumes: 
      - ./database/backup:/usr/src/Eventator/database/backup
      - ./database/data:/usr/src/Eventator/database/data
      - ./database/log:/usr/src/Eventator/database/log
  api:
    image: mjviks/eventator-api
    container_name: eventator_api
    restart: always
    environment:
      MSSQL_HOST: db
      MSSQL_PASS: #pass
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - "db" # старт после старта контейнера db 
  nginx:
    image: nginx:1.17.10
    container_name: eventator_nginx
    restart: always
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/api.eventatorapp.com/fullchain.pem:/etc/ssl/fullchain.pem
      - /etc/letsencrypt/live/api.eventatorapp.com/privkey.pem:/etc/ssl/privkey.pem
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/src/html
    links:
      - api
    ports:
      - 443:443
      - 80:80
    

